# Generated by Django 3.1.5 on 2021-01-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField()),
                ('video_url', models.CharField(max_length=255)),
                ('sourse_code', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='lesson_img')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.project')),
            ],
        ),
    ]
